# Generated by Django 4.2.4 on 2023-08-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(default='Bu foniy dunyo hayotini adolatli deb boʻlmaydi.'),
            preserve_default=False,
        ),
    ]
